version: '2.2'
services:
  logstash:
    image: liatrio-logstash
    build: ./logstash
  logstash-jenkins:
    image: liatrio-logstash-jenkins
    build: ./logstash-jenkins
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.0
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://ec2-52-34-166-55.us-west-2.compute.amazonaws.com:9200
  jenkins:
    image: jenkins/jenkins
    ports:
      - 8080:8080
    environment:
      - "JAVA_OPTS=-Dorg.apache.commons.jelly.tags.fmt.timeZone=America/Los_Angeles"
    volumes:
      - jenkinsdata:/var/jenkins_home

volumes:
  esdata1:
    driver: local
  jenkinsdata:
    driver: local
