version: '2.2'
services:
  logstash:
    image: liatrio-logstash
    build: ./logstash
    volumes: 
      - ./logstash/pipeline/:/usr/share/logstash/pipeline/
      - ./logstash/plugins/:/usr/share/logstash/plugins/
  logstash-jenkins:
    image: liatrio-logstash-jenkins
    build: ./logstash-jenkins
    volumes: 
      - ./logstash/pipeline/:/usr/share/logstash-jenkins/pipeline/
